version: 2
updates:

  # Enable Security Alerts
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "npm"
      include: "scope"
    open-pull-requests-limit: 0
